apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts: 
    - name: nfs-pvc
      mountPath: /var/data 
  volumes: 
  - name: nfs-pvc 
    persistentVolumeClaim:
      claimName: hello-nfs-pvc