apiVersion: v1
kind: Pod
metadata:
  name: oom-killed-pod
spec:
  containers:
  - name: memory-hog
    image: python:3.9-alpine
    command: ["python", "-c", "a = ' ' * (1024 * 1024 * 200)"] # Allocates 200MB
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
