---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - "3600"
          readinessProbe:
            exec:
              command:
              - ls
              - /var/ready
          livenessProbe:
            exec:
              command:
              - ls
              - /var/www
