apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-chart.fullname" . }}
  labels:
    {{- include "test-chart.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.extraLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
spec:
  replicas: {{ default 2 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "test-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "test-chart.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ required "Image repository is required!" .Values.image.repository }}:{{ default "latest" .Values.image.tag }}'
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
          {{- range .Values.config.ENV_VARS }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "test-chart.fullname" $ }}
                  key: {{ .name }}
          {{- end }}
      {{- if .Values.enableSidecar }}
        - name: {{ .Values.sidecar.name }}
          image: {{ .Values.sidecar.image }}
          command: {{ .Values.sidecar.command }}
      {{- end }}
