apiVersion: v1
kind: Pod
metadata:
  name: configmap-as-file
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "while true; do echo $(cat /config/APP_MODE) && sleep 10; done"]
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: my-config
