apiVersion: v1
kind: Pod
metadata:
  name: configmap-valuefrom
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo APP_MODE=$APP_MODE && sleep 3600"]
      env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_MODE
