apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-subchart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "my-subchart.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/app-name: {{ .Values.global.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-subchart.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "my-subchart.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "my-subchart.fullname" . }}
          image: '{{ .Values.image.repository }}:{{ .Values.global.imageTag }}'
          ports:
            - containerPort: {{ .Values.service.port }}
