replicaCount: 2

image:
  repository: nginx
  tag: "1.21"

enableSidecar: false

sidecar:
  name: log-agent
  image: busybox
  command: ["/bin/sh", "-c", "echo Hello"]

service:
  enabled: true
  type: ClusterIP
  port: 80

config:
  ENV_VARS:
    - name: "WELCOME_MESSAGE"
      value: "Hello from Helm!"
    - name: "ENV"
      value: "production"

extraLabels:
  team: devops
  owner: alice
  feature: "v2"


global:
  appName: demo-app
  imageTag: "1.21"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

my-subchart:
  enabled: true
  service:
    port: 8080
  image:
    repository: nginx
