apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
  labels:
    app: init-demo
spec:
  containers:
  - name: main-container
    image: busybox:latest
    command: ['sh', '-c', 'echo Hello from the main container! && sleep 3600']
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ['sh', '-c', 'echo Initializing... && sleep 30']